### ISSUE TITLE
Re-package 1.5.1 noarch for cwltool

### ISSUE THREAD

**Issue by croth1** [conda-forge/prov-feedstock#10]
Would it be possible to repackage prov 1.5.1 noarch? Unfortunately we need it for getting the python 3.7 support in cwltool.

I'm not sure how this is done best. Would it work to build it in a temporary separate branch?

**Comment by mariusvniekerk** [comment]
yeah we can make a branch for it, but it seems like the true reason for needing to rely on this pin is best solved upstream in cwtool itself

**Comment by croth1** [comment]
This is done. Thanks @mariusvniekerk for help and discussion.
