### ISSUE TITLE
pydot missing

### ISSUE THREAD

**Issue by lsetiawan** [conda-forge/prov-feedstock#6]
It seems that `pydot` requirement is missing. I noticed that in https://github.com/conda-forge/prov-feedstock/blob/master/recipe/meta.yaml#L23 `pydotplus` is used, but seems like [`prov` still uses the old `pydot`](https://github.com/trungdong/prov/blob/master/requirements.txt#L5).

**Comment by trungdong** [comment]
Hello,

`pydotplus` was used previously due to `pydot`'s lack of support for Python 3. This has now been addressed and `prov` is using `pydot` again.

`pydotplus` can be removed from the requirements and replaced by `pydot`.

**Comment by lsetiawan** [comment]
Thanks I will fix the recipe with the current requirements.
